language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "let build reverse proxy service"

script:
  - docker --version # print the version for logging
  - docker build -t udagram-reverseproxy .
  # Tagging
  - docker tag udagram-reverseproxy lxmhoang/udagram-reverseproxy:v2
  
after_success:
# Push
# Assuming DOCKER_PASSWORD and DOCKER_USERNAME are set in the Travis repository settings
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push lxmhoang/udagram-reverseproxy:v2
